linters:
  # Defaults, plus:
  enable:
  - errname
  - errorlint
  - exportloopref
  - gocritic
  - godot
  - goheader
  - goimports
  - gosec
  - lll
  - makezero
  - misspell
  - nilerr
  - nilnil
  - nolintlint
  - prealloc
  - revive
  - unconvert
  - unparam
  - whitespace
