version: "2"
linters:
  enable:
    - errname
    - errorlint
    - gocritic
    - godot
    - goheader
    - gosec
    - lll
    - makezero
    - misspell
    - nilerr
    - nilnil
    - nolintlint
    - prealloc
    - revive
    - unconvert
    - unparam
    - whitespace

formatters:
  enable:
    - goimports
